name: 'GsCheck'

on:
  push:
    branches: 
      - main
  schedule: 
    - cron: "5 16,22 * * *"
jobs:
  Gs-Check:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout codes'
        uses: actions/checkout@v2
      - name: 'set python'
        uses: actions/setup-python@v1
        with:
          python-version: "3.8.16"
      - name: 'Install dependencies'
        run: python -m pip install --upgrade

      - name: 'start'
        env:
          gsurl: ${{ secrets.GSURL }}
          gs_ck: ${{ secrets.GS_CK }}
          gktk: ${{ secrets.GKTK }}
          ddtk: ${{ secrets.DDTK }}
        run: python main.py
